POST  http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbWUyIiwiaWQiOiI1YzBiMjUxMWRiNDg0NjViODQxOTJjMmQiLCJpYXQiOjE1NDQyODE1NjV9.hLP9x8wdhO11gI4Qmm4-bv7QmUq6vErLyvZwWlMOkWs

{
    "title": "Test Blog",
    "author": "Some one",
    "url": "www.asfd.com",
    "likes": 0
}